name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - citest
  pull_request:
    branches:
      - citest

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install caesar
        # update pip so we can install from git URLs
        # numpy and cython are required for yt because its setup.py is dumb
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user setuptools numpy cython
          cd /home/runner/work/caesar/caesar
          python3 -m pip install --user .

      - name: Download FIRE snapshot
        run: |
          curl -LO http://yt-project.org/data/FIRE_M12i_ref11.tar.gz
          tar xvf FIRE_M12i_ref11.tar.gz
          rm FIRE_M12i_ref11.tar.gz

      - name: Test FIRE snapshot
        run: python3 scripts/commit_tests.py FIRE_M12i_ref11/snapshot_600.hdf5
