name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - citest
  pull_request:
    branches:
      - citest

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: gizmo_64
        run: |
          python3 -m pip install setuptools
          python3 -m pip install .
          cd scripts/
          curl -LO http://yt-project.org/data/gizmo_64.tar.gz
          tar xf gizmo_64.tar.gz
          python commit_tests.py gizmo_64/output/snap_N64L16_000.hdf5 gizmo_64/output/snap_N64L16_135.hdf5
