name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - citest
  pull_request:
    branches:
      - citest

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install caesar
        # update pip so we can install from git URLs
        # numpy and cython are required for yt because its setup.py is dumb
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user setuptools numpy cython
          cd /home/runner/work/caesar/caesar
          python3 -m pip install --user .

      - name: Download gizmo_64
        run: |
          curl -LO http://yt-project.org/data/gizmo_64.tar.gz
          tar xvf gizmo_64.tar.gz
          rm gizmo_64.tar.gz

      - name: Test gizmo_64
        run: python3 scripts/commit_tests.py gizmo_64/output/snap_N64L16_135.hdf5
