name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - citest
  pull_request:
    branches:
      - citest

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Init
        run: mkdir ~/datasets

      - name: Cache datasets
        uses: actions/cache@v1
        env:
          cache-name: cache-datasets
        with:
          path: ~/datasets
          key: ${{ env.cache-name }}

      - name: Download datasets
        run: |
          cd ~/datasets/
          curl -LO http://yt-project.org/data/gizmo_64.tar.gz
          tar xf gizmo_64.tar.gz

      - name: Install dependencies
        run: |
          cd
          python3 -m pip install --user setuptools
          python3 -m pip install --user wheel
          python3 -m pip install --user numpy cython
          git clone https://github.com/yt-project/yt
          cd yt
          git checkout yt-4.0
          python3 -m pip install --user .
          cd ..
          git clone https://github.com/dnarayanan/pygadgetreader
          cd pygadgetreader
          python3 -m pip install --user .

      - name: Install caesar
        run: |
          cd /home/runner/work/caesar/caesar
          python3 -m pip install --user .

      - name: gizmo_64
        run: |
          cd /home/runner/work/caesar/caesar
          python3 scripts/commit_tests.py ~/datasets/gizmo_64/output/snap_N64L16_000.hdf5 ~/datasets/gizmo_64/output/snap_N64L16_135.hdf5
